services:
  ratings:
    build: .
    image: ghcr.io/wsboos/bookinfo-ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
  mongodb:
    image : bitnami/mongodb:latest
    volumes :
      - ~/ratings/databases:/docker-entrypoint-initdb.d
    

